version: '3.9'

services:

  haproxy:
    image: haproxy:2.8.1-alpine
    container_name: sndb_haproxy
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      frontend:
        ipv4_address: 172.23.8.2
      backend:
        ipv4_address: 172.23.9.2

  web_1:
    image: nginx:1.25-alpine
    container_name: sndb_nginx_1
    ports:
      - "8081:80"
    volumes:
      - ./nginx_1/html:/usr/share/nginx/html
    networks:
      backend:
        ipv4_address: 172.23.9.3

  web_2:
    image: nginx:1.25-alpine
    container_name: sndb_nginx_2
    ports:
      - "8082:80"
    volumes:
      - ./nginx_2/html:/usr/share/nginx/html
    networks:
      backend:
        ipv4_address: 172.23.9.4

networks:

  frontend:
    name: sndb_frontend
    ipam:
      config:
        - subnet: "172.23.8.0/24"
          gateway: 172.23.8.1

  backend:
    name: sndb_backend
    ipam:
      config:
        - subnet: "172.23.9.0/24"
          gateway: 172.23.9.1

